apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
  - name: webserver01
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
      - name: configmap-volume
        mountPath: /etc/config
  - name: webwatcher
    image: afakharany/watcher:latest
    volumeMounts:
      - name: configmap-volume
        mountPath: /etc/config
  volumes:
  - name: configmap-volume
    configMap:
      name: cm-test