version: '3.2'
services:
  # debug network util
  tool:
    image: praqma/network-multitool
    networks:
      - graylog
  fluentd:
    image: fluent/fluentd:v1.12-1
    volumes:
      - ./conf:/fluentd/etc/
      - ./sample_log:/var/log
    ports:
      - "8888:8888"
      - "24224:24224"
      - "24224:24224/udp"
networks:
  graylog:
    driver: bridge